baseURL = "/"
languageCode = "en-us"
title = "Rajmahendra"
enableEmoji=true
theme = "ink"
paginate = 5

copyright = "© Copyright Rajmahendra"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "rajmahendra-me"


[permalinks]
  posts = "/blog/:year/:title/"

[params]
    customCss = "css/gallery.css"

	subtitle = "I have no special talents. I am only passionately curious"

	# Optional 64x64 avatar image.
	avatar = "/images/icon.png"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4


[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/rajmahendrar"

[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://facebook.com/rajmahendrar"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/rajmahendra"

[[params.social]]
name = "Slideshare"
icon = "slideshare"
url = "https://www2.slideshare.net/rajmahendra"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
